name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to create'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          extensions: none, curl, dom, mbstring, simplexml, tokenizer, xml, xmlwriter, json, fileinfo
          coverage: none

      - run: composer install --no-dev

      - run: chmod 777 -R vendor

      - run: git archive --output=tpay-openapi-php.zip HEAD

      - run: zip -ur tpay-openapi-php.zip vendor/

      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          name: "v${{ github.event.inputs.version }}"
          generateReleaseNotes: true
          artifacts: tpay-openapi-php.zip

