name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: git archive --output=tpay-openapi-php.zip HEAD

      - uses: softprops/action-gh-release@v1
        with:
          files: tpay-openapi-php.zip
